In [2]:
import torch
A=torch.arange(24).reshape(2,3,4)
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

**Based on the tensor shape**
- shape(a,b,c)
- axis 0 -- operate along a
- axis 1 -- operate along b
- axis 2 -- operate along c
- Dimension reduction

In [3]:
A.sum(axis=0),A.sum(axis=0).shape,A.sum(axis=1),A.sum(axis=1).shape,A.sum(axis=2),A.sum(axis=2).shape,A.sum(axis=[0, 1]),A.sum(axis=[0, 1]).shape

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 torch.Size([2, 4]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]),
 torch.Size([2, 3]),
 tensor([60, 66, 72, 78]),
 torch.Size([4]))

**same dimension but not neccesary same shape**

In [4]:
A.sum(axis=0, keepdims=True),A.sum(axis=0, keepdims=True).shape

(tensor([[[12, 14, 16, 18],
          [20, 22, 24, 26],
          [28, 30, 32, 34]]]),
 torch.Size([1, 3, 4]))

In [5]:
X=torch.ones(2,2,4)
Y=torch.ones(2,4,2)
X,Y,torch.matmul(X,Y)

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 tensor([[[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]]]),
 tensor([[[4., 4.],
          [4., 4.]],
 
         [[4., 4.],
          [4., 4.]]]))